nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

packageExtensions:
  esbuild-loader@*:
    dependencies:
      webpack: ^5.72.1

defaultSemverRangePrefix: ""

yarnPath: .yarn/releases/yarn-3.2.0.cjs
