compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  esbuild-loader@*:
    dependencies:
      webpack: ^5.72.1

yarnPath: .yarn/releases/yarn-4.1.1.cjs
