nodeLinker: pnp

packageExtensions:
  # TODO: remove with docusaurus 2.0.0-beta.19 - https://github.com/facebook/docusaurus/pull/7014
  "@docusaurus/types@*":
    dependencies:
      history: 4.9.0
      "react-loadable": "npm:@docusaurus/react-loadable@5.5.2"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
