name: setup-node-pnpm
description: Setup Node and PNPM
runs:
  using: "composite"
  steps:
    - name: cache output directories
      uses: actions/cache@v4
      with:
        path: |
          .astro
          .cache
          dist
          node_modules
        key: ${{ runner.os }}-output-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-output-${{ hashFiles('**/pnpm-lock.yaml') }}
          ${{ runner.os }}-output-
    - name: "setup pnpm"
      uses: "pnpm/action-setup@v4"
    - name: "setup node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 22
