<permission>:
  default:
    description: |
      Who this permission is granted to by default

      "true": all players

      "false": no players

      "op": only operators (also aliased as "isop", "operator", "isoperator", "admin", and "isadmin")

      "!op": all players except operators (also aliased as "notop", "!operator", "notoperator", "!admin", "notadmin")
    default: "op"
  children:
    header:
      message:
        A list (not shown) or a map (shown below) of child permissions
    <permission>:
      description: |
        A child permission of this permission.

        The value is either a boolean, where false inverts the whether the permission would be granted to this.

        or a top level permission entry,
        except the default is this parent permissions default value,
        and any child permissions of the newly created permission are bubbled up to the top level.
      default: "true"
  description_:
    description: |
      The description of the permission.
    default: "\"\""
